GTCEuStartupEvents.registry("gtceu:material", event => {
  event.create("redstone_glowstone_mixture")
    .liquid(new GTFluidBuilder().temperature(850))
    .components("1x redstone", "1x glowstone")
    .color(0xD9783F)
    .iconSet(GTMaterialIconSet.SHINY)
    .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

  event.create("red_brass")
    .dust()
    .ingot()
    .liquid(new GTFluidBuilder().temperature(1025))
    .components("6x copper", "2x tin", "1x zinc")
    .color(0xC45649)
    .iconSet(GTMaterialIconSet.METALLIC)
    .flags(GTMaterialFlags.GENERATE_PLATE)
    .cableProperties(GTValues.V[GTValues.ULV], 1, 0, true)
    .itemPipeProperties(1024, 2)
})
